// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.6.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:ffi' as ffi;

abstract class VelumCore {
  Future<String> helloVelum({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kHelloVelumConstMeta;

  Future<String> getSampleDocument({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetSampleDocumentConstMeta;

  Future<int> multiply({required int a, required int b, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMultiplyConstMeta;

  Future<String> createEmptyDocument({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCreateEmptyDocumentConstMeta;

  Future<String> insertText({
    required int offset,
    required String newText,
    dynamic hint,
  });

  FlutterRustBridgeTaskConstMeta get kInsertTextConstMeta;

  Future<String> deleteText({
    required int offset,
    required int length,
    dynamic hint,
  });

  FlutterRustBridgeTaskConstMeta get kDeleteTextConstMeta;

  Future<String> getTextRange({
    required int offset,
    required int length,
    dynamic hint,
  });

  FlutterRustBridgeTaskConstMeta get kGetTextRangeConstMeta;

  Future<int> getLineCount({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetLineCountConstMeta;

  Future<String?> getLineContent({required int lineNumber, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetLineContentConstMeta;

  Future<String> getFullText({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetFullTextConstMeta;

  Future<String> undo({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kUndoConstMeta;

  Future<String> redo({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRedoConstMeta;

  Future<bool> canUndo({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCanUndoConstMeta;

  Future<bool> canRedo({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCanRedoConstMeta;
}

class VelumCoreImpl implements VelumCore {
  final VelumCorePlatform _platform;
  factory VelumCoreImpl(ExternalLibrary dylib) =>
      VelumCoreImpl.raw(VelumCorePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory VelumCoreImpl.wasm(FutureOr<WasmModule> module) =>
      VelumCoreImpl(module as ExternalLibrary);
  VelumCoreImpl.raw(this._platform);
  Future<String> helloVelum({dynamic hint}) {
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_hello_velum(port_),
        parseSuccessData: _wire2api_String,
        parseErrorData: null,

        constMeta: kHelloVelumConstMeta,
        argValues: [],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kHelloVelumConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "hello_velum",
        argNames: [],
      );

  Future<String> getSampleDocument({dynamic hint}) {
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_get_sample_document(port_),
        parseSuccessData: _wire2api_String,
        parseErrorData: null,

        constMeta: kGetSampleDocumentConstMeta,
        argValues: [],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kGetSampleDocumentConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_sample_document",
        argNames: [],
      );

  Future<int> multiply({required int a, required int b, dynamic hint}) {
    var arg0 = api2wire_i32(a);
    var arg1 = api2wire_i32(b);
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_multiply(port_, arg0, arg1),
        parseSuccessData: _wire2api_i32,
        parseErrorData: null,

        constMeta: kMultiplyConstMeta,
        argValues: [a, b],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kMultiplyConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "multiply",
        argNames: ["a", "b"],
      );

  Future<String> createEmptyDocument({dynamic hint}) {
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_create_empty_document(port_),
        parseSuccessData: _wire2api_String,
        parseErrorData: null,

        constMeta: kCreateEmptyDocumentConstMeta,
        argValues: [],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kCreateEmptyDocumentConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "create_empty_document",
        argNames: [],
      );

  Future<String> insertText({
    required int offset,
    required String newText,
    dynamic hint,
  }) {
    var arg0 = api2wire_usize(offset);
    var arg1 = _platform.api2wire_String(newText);
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_insert_text(port_, arg0, arg1),
        parseSuccessData: _wire2api_String,
        parseErrorData: null,

        constMeta: kInsertTextConstMeta,
        argValues: [offset, newText],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kInsertTextConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "insert_text",
        argNames: ["offset", "newText"],
      );

  Future<String> deleteText({
    required int offset,
    required int length,
    dynamic hint,
  }) {
    var arg0 = api2wire_usize(offset);
    var arg1 = api2wire_usize(length);
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_delete_text(port_, arg0, arg1),
        parseSuccessData: _wire2api_String,
        parseErrorData: null,

        constMeta: kDeleteTextConstMeta,
        argValues: [offset, length],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kDeleteTextConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "delete_text",
        argNames: ["offset", "length"],
      );

  Future<String> getTextRange({
    required int offset,
    required int length,
    dynamic hint,
  }) {
    var arg0 = api2wire_usize(offset);
    var arg1 = api2wire_usize(length);
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) =>
            _platform.inner.wire_get_text_range(port_, arg0, arg1),
        parseSuccessData: _wire2api_String,
        parseErrorData: null,

        constMeta: kGetTextRangeConstMeta,
        argValues: [offset, length],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kGetTextRangeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_text_range",
        argNames: ["offset", "length"],
      );

  Future<int> getLineCount({dynamic hint}) {
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_get_line_count(port_),
        parseSuccessData: _wire2api_usize,
        parseErrorData: null,

        constMeta: kGetLineCountConstMeta,
        argValues: [],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kGetLineCountConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_line_count",
        argNames: [],
      );

  Future<String?> getLineContent({required int lineNumber, dynamic hint}) {
    var arg0 = api2wire_usize(lineNumber);
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_get_line_content(port_, arg0),
        parseSuccessData: _wire2api_opt_String,
        parseErrorData: null,

        constMeta: kGetLineContentConstMeta,
        argValues: [lineNumber],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kGetLineContentConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_line_content",
        argNames: ["lineNumber"],
      );

  Future<String> getFullText({dynamic hint}) {
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_get_full_text(port_),
        parseSuccessData: _wire2api_String,
        parseErrorData: null,

        constMeta: kGetFullTextConstMeta,
        argValues: [],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kGetFullTextConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_full_text",
        argNames: [],
      );

  Future<String> undo({dynamic hint}) {
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_undo(port_),
        parseSuccessData: _wire2api_String,
        parseErrorData: null,

        constMeta: kUndoConstMeta,
        argValues: [],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kUndoConstMeta =>
      const FlutterRustBridgeTaskConstMeta(debugName: "undo", argNames: []);

  Future<String> redo({dynamic hint}) {
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_redo(port_),
        parseSuccessData: _wire2api_String,
        parseErrorData: null,

        constMeta: kRedoConstMeta,
        argValues: [],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kRedoConstMeta =>
      const FlutterRustBridgeTaskConstMeta(debugName: "redo", argNames: []);

  Future<bool> canUndo({dynamic hint}) {
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_can_undo(port_),
        parseSuccessData: _wire2api_bool,
        parseErrorData: null,

        constMeta: kCanUndoConstMeta,
        argValues: [],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kCanUndoConstMeta =>
      const FlutterRustBridgeTaskConstMeta(debugName: "can_undo", argNames: []);

  Future<bool> canRedo({dynamic hint}) {
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_can_redo(port_),
        parseSuccessData: _wire2api_bool,
        parseErrorData: null,

        constMeta: kCanRedoConstMeta,
        argValues: [],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kCanRedoConstMeta =>
      const FlutterRustBridgeTaskConstMeta(debugName: "can_redo", argNames: []);

  void dispose() {
    _platform.dispose();
  }
  // Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  int _wire2api_i32(dynamic raw) {
    return raw as int;
  }

  String? _wire2api_opt_String(dynamic raw) {
    return raw == null ? null : _wire2api_String(raw);
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  int _wire2api_usize(dynamic raw) {
    return castInt(raw);
  }

  bool _wire2api_bool(dynamic raw) {
    return raw as bool;
  }
}

// Section: api2wire

@protected
int api2wire_i32(int raw) {
  return raw;
}

@protected
int api2wire_u8(int raw) {
  return raw;
}

@protected
int api2wire_usize(int raw) {
  return raw;
}
// Section: finalizer

class VelumCorePlatform extends FlutterRustBridgeBase<VelumCoreWire> {
  VelumCorePlatform(ffi.DynamicLibrary dylib) : super(VelumCoreWire(dylib));

  // Section: api2wire

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
    return api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  // Section: finalizer

  // Section: api_fill_to_wire
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class VelumCoreWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  VelumCoreWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  VelumCoreWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(int ptr) {
    return _get_dart_object(ptr);
  }

  late final _get_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>(
        'get_dart_object',
      );
  late final _get_dart_object = _get_dart_objectPtr
      .asFunction<Object Function(int)>();

  void drop_dart_object(int ptr) {
    return _drop_dart_object(ptr);
  }

  late final _drop_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
        'drop_dart_object',
      );
  late final _drop_dart_object = _drop_dart_objectPtr
      .asFunction<void Function(int)>();

  int new_dart_opaque(Object handle) {
    return _new_dart_opaque(handle);
  }

  late final _new_dart_opaquePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>(
        'new_dart_opaque',
      );
  late final _new_dart_opaque = _new_dart_opaquePtr
      .asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(ffi.Pointer<ffi.Void> obj) {
    return _init_frb_dart_api_dl(obj);
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
        'init_frb_dart_api_dl',
      );
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_hello_velum(int port_) {
    return _wire_hello_velum(port_);
  }

  late final _wire_hello_velumPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'wire_hello_velum',
      );
  late final _wire_hello_velum = _wire_hello_velumPtr
      .asFunction<void Function(int)>();

  void wire_get_sample_document(int port_) {
    return _wire_get_sample_document(port_);
  }

  late final _wire_get_sample_documentPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'wire_get_sample_document',
      );
  late final _wire_get_sample_document = _wire_get_sample_documentPtr
      .asFunction<void Function(int)>();

  void wire_multiply(int port_, int a, int b) {
    return _wire_multiply(port_, a, b);
  }

  late final _wire_multiplyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32, ffi.Int32)>
      >('wire_multiply');
  late final _wire_multiply = _wire_multiplyPtr
      .asFunction<void Function(int, int, int)>();

  void wire_create_empty_document(int port_) {
    return _wire_create_empty_document(port_);
  }

  late final _wire_create_empty_documentPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'wire_create_empty_document',
      );
  late final _wire_create_empty_document = _wire_create_empty_documentPtr
      .asFunction<void Function(int)>();

  void wire_insert_text(
    int port_,
    int offset,
    ffi.Pointer<wire_uint_8_list> new_text,
  ) {
    return _wire_insert_text(port_, offset, new_text);
  }

  late final _wire_insert_textPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_uint_8_list>,
          )
        >
      >('wire_insert_text');
  late final _wire_insert_text = _wire_insert_textPtr
      .asFunction<void Function(int, int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_delete_text(int port_, int offset, int length) {
    return _wire_delete_text(port_, offset, length);
  }

  late final _wire_delete_textPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.UintPtr)
        >
      >('wire_delete_text');
  late final _wire_delete_text = _wire_delete_textPtr
      .asFunction<void Function(int, int, int)>();

  void wire_get_text_range(int port_, int offset, int length) {
    return _wire_get_text_range(port_, offset, length);
  }

  late final _wire_get_text_rangePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.UintPtr)
        >
      >('wire_get_text_range');
  late final _wire_get_text_range = _wire_get_text_rangePtr
      .asFunction<void Function(int, int, int)>();

  void wire_get_line_count(int port_) {
    return _wire_get_line_count(port_);
  }

  late final _wire_get_line_countPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'wire_get_line_count',
      );
  late final _wire_get_line_count = _wire_get_line_countPtr
      .asFunction<void Function(int)>();

  void wire_get_line_content(int port_, int line_number) {
    return _wire_get_line_content(port_, line_number);
  }

  late final _wire_get_line_contentPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'wire_get_line_content',
      );
  late final _wire_get_line_content = _wire_get_line_contentPtr
      .asFunction<void Function(int, int)>();

  void wire_get_full_text(int port_) {
    return _wire_get_full_text(port_);
  }

  late final _wire_get_full_textPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'wire_get_full_text',
      );
  late final _wire_get_full_text = _wire_get_full_textPtr
      .asFunction<void Function(int)>();

  void wire_undo(int port_) {
    return _wire_undo(port_);
  }

  late final _wire_undoPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>('wire_undo');
  late final _wire_undo = _wire_undoPtr.asFunction<void Function(int)>();

  void wire_redo(int port_) {
    return _wire_redo(port_);
  }

  late final _wire_redoPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>('wire_redo');
  late final _wire_redo = _wire_redoPtr.asFunction<void Function(int)>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(int len) {
    return _new_uint_8_list_0(len);
  }

  late final _new_uint_8_list_0Ptr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<wire_uint_8_list> Function(ffi.Int32)>
      >('new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturn(WireSyncReturn ptr) {
    return _free_WireSyncReturn(ptr);
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>(
        'free_WireSyncReturn',
      );
  late final _free_WireSyncReturn = _free_WireSyncReturnPtr
      .asFunction<void Function(WireSyncReturn)>();
}

final class _Dart_Handle extends ffi.Opaque {}

final class BufferId extends ffi.Opaque {}

final class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

typedef DartPostCObjectFnType =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)
      >
    >;
typedef DartPort = ffi.Int64;
